#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config border_width         1
bspc config window_gap           6

bspc config active_border_color '#282C34'
bspc config normal_border_color '#282C34'
bspc config focused_border_color '#61AFEF'

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_follows_pointer       true
bspc config history_aware_focus         true


bspc config bottom_padding                0
bspc config left_padding                  0
bspc config right_padding                 0


bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off


# auto start
sh ~/.config/polybar/launch.sh &

feh --bg-fill ~/wallpapers/nordic.jpg
 
# volumeicon &

sh ~/.config/i3/ibus.sh &

xset r rate 200 36 &

cpupower-gui -p &

killall gsettings-helper &

# picom --config ~/.config/picom/picom.conf
