;(package! builtin-package :disable t)
;;(package! auto-yasnippet :disable t)
(package! smex :recipe (:host github :repo "nonsequitur/smex"))
(package! zenburn-theme)
(package! gruber-darker-theme)
(package! hl-line :disable t)
(package! rust-mode)
(unpin! straight)
