;(package! builtin-package :disable t)
;;(package! auto-yasnippet :disable t)
(package! smex :recipe (:host github :repo "nonsequitur/smex"))
(package! zenburn-theme)
(package! monokai-theme)
(package! solarized-theme)
(package! rust-mode)
; (package! gruber-darker-theme)
(package! hl-line :disable t)
(package! atom-one-dark-theme)
